name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.17

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2

    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
